"""SG Office -- the formula corpus's report (Markdown): a summary, then every
function with its cases' results. Written by corpus.py --report.

Copyright (C) 2026 Stained Glass OS contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""
import datetime

WORD = {"match": "matches Excel", "differs": "differs", "missing": "missing", "export": "export differs"}


def md(s):
    return s.replace("|", "\\|")


def write(path, cases, engine=""):
    funcs = {}
    for c in cases:
        funcs.setdefault((c.category, c.name), []).append(c)

    def fstatus(cs):
        st = {c.status for c in cs}
        if st == {"match"}:
            return "supported"
        if st == {"missing"}:
            return "missing"
        return "partly" if "match" in st else ("missing" if "missing" in st else "differs")

    per = {k: fstatus(v) for k, v in funcs.items()}
    n = {s: sum(1 for v in per.values() if v == s) for s in ("supported", "partly", "differs", "missing")}
    nc = {s: sum(1 for c in cases if c.status == s) for s in WORD}
    import sys, os
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "functions"))
    from sgoffice_spec import FUNCTIONS
    ours = sorted(n for _m, n, *_ in FUNCTIONS)
    out = ["# SG Office: Excel formula compatibility", "",
           "Generated by `office/parity/corpus.py` on %s%s. Every case is a formula as Excel writes it "
           "in a workbook (\"_xlfn.\" prefixes and all); the expected value is Excel's, from its documentation "
           "and known behaviour. The workbook is opened in SG Office, recalculated, saved back to .xlsx, and "
           "each result and each function's saved name checked." % (datetime.date.today().isoformat(),
                                                                      " against " + engine if engine else ""), "",
           "SG Office Functions, our add-in, provides: %s." % ", ".join(ours), "",
           "**Functions:** %d supported, %d partly (some cases differ), %d differ, %d missing -- of %d tested."
           % (n["supported"], n["partly"], n["differs"], n["missing"], len(per)), "",
           "**Cases:** %d match Excel, %d differ, %d missing, %d right but saved differently -- of %d."
           % (nc["match"], nc["differs"], nc["missing"], nc["export"], len(cases)), ""]
    for label, want in (("Missing functions", "missing"), ("Functions that differ", "differs"),
                        ("Functions that partly differ", "partly")):
        names = sorted(k[1] for k, v in per.items() if v == want)
        if names:
            out += ["**%s (%d):** %s" % (label, len(names), ", ".join(names)), ""]
    cat = None
    for (category, name), cs in funcs.items():
        if category != cat:
            cat = category
            out += ["", "## " + category, "", "| Function | Formula | Excel | SG Office | Result |", "|---|---|---|---|---|"]
        for c in cs:
            from corpus import describe_expected
            res = WORD[c.status] + (" -- " + c.note if c.note else "")
            out.append("| %s | `=%s` | %s | %s | %s |" % (md(c.name), md(c.formula), md(describe_expected(c.expected)),
                                                          md(c.shown), md(res)))
    open(path, "w", encoding="utf-8").write("\n".join(out) + "\n")
