#!/usr/bin/python3
"""Builds the SG Office Functions extension from sgoffice_spec.py.

    build-oxt.py DIR        the unpacked extension (what the package installs
                            under /usr/lib/libreoffice/share/extensions/)
    build-oxt.py FILE.oxt   the same, zipped (what a gate installs with unopkg)

The type library is the .idl itself: LibreOffice reads UNO types from IDL
source, so no IDL compiler is needed to build it.

Copyright (C) 2026 Stained Glass OS contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""
import os
import shutil
import sys
import tempfile
import zipfile
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from sgoffice_spec import FUNCTIONS, IMPL, INTERFACE, VERSION  # noqa: E402

# categories as Calc's Function Wizard names them
CATEGORY = {"Text": "Text", "Spreadsheet": "Spreadsheet", "Mathematical": "Mathematical",
            "Statistical": "Statistical", "Add-In": "Add-In"}


def ident(p):
    """An IDL identifier (no underscores) for Excel's parameter name."""
    head, *rest = p.split("_")
    return head + "".join(w.capitalize() for w in rest)


def idl():
    mod, iface = INTERFACE.rsplit(".", 1)
    parts = mod.split(".")
    out = ["// SG Office Functions: the add-in's interface (generated by build-oxt.py)."]
    out.append(" ".join("module %s {" % p for p in parts))
    out.append("interface %s : com::sun::star::uno::XInterface" % iface)
    out.append("{")
    for m, _n, _x, _c, _d, params, ret in FUNCTIONS:
        rt = "sequence< sequence< any > >" if ret == "array" else "any"
        ps = ", ".join("[in] %s %s" % ("sequence< any >" if k == "rest" else "any", ident(p)) for p, _pd, k in params)
        out.append("    %s %s(%s);" % (rt, m, ps))
    out.append("};")
    out.append(" ".join("};" for _ in parts))
    return "\n".join(out) + "\n"


def xcu():
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<oor:component-data xmlns:oor="http://openoffice.org/2001/registry" '
           'xmlns:xs="http://www.w3.org/2001/XMLSchema" oor:name="CalcAddIns" oor:package="org.openoffice.Office">',
           '<node oor:name="AddInInfo">',
           '<node oor:name="%s" oor:op="replace">' % IMPL, '<node oor:name="AddInFunctions">']
    for m, name, excel, cat, desc, params, _r in FUNCTIONS:
        out.append('<node oor:name="%s" oor:op="replace">' % m)
        out.append('<prop oor:name="DisplayName"><value xml:lang="en-US">%s</value></prop>' % escape(name))
        out.append('<prop oor:name="Description"><value xml:lang="en-US">%s</value></prop>' % escape(desc))
        out.append('<prop oor:name="Category"><value>%s</value></prop>' % CATEGORY[cat])
        out.append('<prop oor:name="CompatibilityName"><value xml:lang="en-US">%s</value></prop>' % escape(excel))
        out.append('<node oor:name="Parameters">')
        for p, pd, _k in params:
            out.append('<node oor:name="%s" oor:op="replace">'
                       '<prop oor:name="DisplayName"><value xml:lang="en-US">%s</value></prop>'
                       '<prop oor:name="Description"><value xml:lang="en-US">%s</value></prop></node>'
                       % (ident(p), escape(p), escape(pd)))
        out.append('</node></node>')
    out.append('</node></node></node></oor:component-data>')
    return "\n".join(out) + "\n"


MANIFEST = """<?xml version="1.0" encoding="UTF-8"?>
<manifest:manifest xmlns:manifest="http://openoffice.org/2001/manifest">
 <manifest:file-entry manifest:full-path="XSgFunctions.idl" manifest:media-type="application/vnd.sun.star.uno-typelibrary;type=RDB"/>
 <manifest:file-entry manifest:full-path="component.py" manifest:media-type="application/vnd.sun.star.uno-component;type=Python"/>
 <manifest:file-entry manifest:full-path="CalcAddIn.xcu" manifest:media-type="application/vnd.sun.star.configuration-data"/>
</manifest:manifest>
"""

DESCRIPTION = """<?xml version="1.0" encoding="UTF-8"?>
<description xmlns="http://openoffice.org/extensions/description/2006"
             xmlns:d="http://openoffice.org/extensions/description/2006"
             xmlns:xlink="http://www.w3.org/1999/xlink">
 <identifier value="org.stainedglass.office.functions"/>
 <version value="%s"/>
 <display-name><name lang="en">SG Office Functions</name></display-name>
 <publisher><name xlink:href="https://github.com/Stained-Glass-OS" lang="en">Stained Glass OS</name></publisher>
 <extension-description><src lang="en" xlink:href="description-en.txt"/></extension-description>
</description>
"""


def build_dir(d):
    if os.path.exists(d):
        shutil.rmtree(d)
    os.makedirs(os.path.join(d, "META-INF"))
    os.makedirs(os.path.join(d, "pythonpath"))
    files = {"XSgFunctions.idl": idl(), "CalcAddIn.xcu": xcu(), "META-INF/manifest.xml": MANIFEST,
             "description.xml": DESCRIPTION % VERSION,
             "description-en.txt": "Spreadsheet functions of Microsoft Excel that the engine lacks, "
                                   "under their Excel names, so workbooks that use them calculate and "
                                   "save as Excel reads them.\n"}
    for name, content in files.items():
        with open(os.path.join(d, name), "w", encoding="utf-8") as f:
            f.write(content)
    shutil.copy(os.path.join(HERE, "component.py"), d)
    for m in ("sgoffice_functions.py", "sgoffice_spec.py"):
        shutil.copy(os.path.join(HERE, m), os.path.join(d, "pythonpath"))


def main(out):
    if out.endswith(".oxt"):
        tmp = tempfile.mkdtemp(dir=os.environ.get("TMPDIR", "/var/tmp"))
        try:
            build_dir(os.path.join(tmp, "x"))
            with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
                for root, _dirs, names in os.walk(os.path.join(tmp, "x")):
                    for n in sorted(names):
                        full = os.path.join(root, n)
                        z.write(full, os.path.relpath(full, os.path.join(tmp, "x")))
        finally:
            shutil.rmtree(tmp)
    else:
        build_dir(out)


if __name__ == "__main__":
    main(sys.argv[1])
