#!/usr/bin/python3
# Character names for sg-charmap's status bar and search, generated at build
# time from the Unicode Character Database (Debian's unicode-data package,
# /usr/share/unicode/UnicodeData.txt; Unicode License v3, which permits
# redistribution of the data and of works derived from it with its notice --
# see debian/copyright). Nothing generated is committed.
#
# The Basic Multilingual Plane only (what GetFontUnicodeRanges reports), in
# title case as Character Map shows them ("Latin Capital Letter A"). Names are
# stored as indices into a word list, which keeps the table small. Ranges the
# database gives as <..., First>/<..., Last> (CJK ideographs, Hangul syllables,
# private use) are named in code.
#
#   gen-names.py [UnicodeData.txt] OUT.c
#
# Copyright (C) 2026 Stained Glass OS contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
import sys

src = sys.argv[1] if len(sys.argv) > 2 else "/usr/share/unicode/UnicodeData.txt"
out = sys.argv[-1]

# acronyms that stay in capitals
KEEP = {"CJK", "APL", "IPA", "ASCII", "OK", "ID", "UK", "TV", "PC", "SOS", "ATM", "WC",
        "DVD", "CD", "NG", "VS", "NKO", "LF", "CR", "FF", "HT", "VT"}


def word_case(w):
    parts = []
    for p in w.split("-"):
        if p in KEEP or any(ch.isdigit() for ch in p):
            parts.append(p)
        else:
            parts.append(p[:1] + p[1:].lower())
    return "-".join(parts)


entries = []
ranges = []          # (first, last, kind): 0 ideograph, 1 Hangul syllable, 2 private use
first = None
for line in open(src, encoding="utf-8"):
    f = line.rstrip("\n").split(";")
    cp = int(f[0], 16)
    if cp > 0xFFFF:
        break
    name = f[1]
    if name.startswith("<"):
        if name == "<control>":
            name = f[10] or "CONTROL"
        elif name.endswith(", First>"):
            first = cp
            continue
        elif name.endswith(", Last>"):
            label = name[1:-len(", Last>")]
            if "Ideograph" in label:
                ranges.append((first, cp, 0))
            elif "Hangul" in label:
                ranges.append((first, cp, 1))
            elif "Private Use" in label and "Surrogate" not in label:
                ranges.append((first, cp, 2))
            continue                # a range: named in code
        else:
            continue
    entries.append((cp, [word_case(w) for w in name.split()]))

words = {}
order = []
for _, ws in entries:
    for w in ws:
        if w not in words:
            words[w] = len(order)
            order.append(w)
assert len(order) < 65536

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '\\0"'

with open(out, "w", encoding="ascii") as o:
    o.write("/* Generated by src/charmap/gen-names.py from the Unicode Character Database. */\n")
    o.write("/* Unicode data (c) Unicode, Inc., under the Unicode License v3. */\n")
    o.write("const char cm_words[] =\n")
    off = []
    pos = 0
    for w in order:
        off.append(pos)
        pos += len(w) + 1
        o.write("    " + cstr(w) + "\n")
    o.write(";\n")
    o.write("const unsigned int cm_word_off[] = {\n" + ",".join(map(str, off)) + "\n};\n")
    o.write("const int cm_count = %d;\n" % len(entries))
    o.write("const int cm_nranges = %d;\n" % len(ranges))
    o.write("const unsigned short cm_range[][3] = {\n" + ",\n".join("{%d,%d,%d}" % r for r in ranges) + "\n};\n")
    o.write("const unsigned short cm_cp[] = {\n" + ",".join(str(cp) for cp, _ in entries) + "\n};\n")
    starts, toks = [], []
    for _, ws in entries:
        starts.append(len(toks))
        toks.extend(words[w] for w in ws)
    starts.append(len(toks))
    o.write("const unsigned int cm_tok_start[] = {\n" + ",".join(map(str, starts)) + "\n};\n")
    o.write("const unsigned short cm_toks[] = {\n" + ",".join(map(str, toks)) + "\n};\n")
